### ISSUE TITLE
app 列表能加上注释吗？

### ISSUE THREAD

**Issue by gee1k** [RenChunhui/dotfiles#3]
app 列表能加上注释吗？
特别时 masfile 里都是 id，根本就不知道那些 app 写了，那些没写
能类似这样吗？:
```
# qq
123456
# weixin
3284736287
```
![image](https://user-images.githubusercontent.com/12059800/68197233-d7d9f780-fff4-11e9-86f4-dca3c81e9ac0.png)

**Comment by RenChunhui** [comment]
这种可以

Svend <notifications@github.com> 于 2019年11月5日周二 下午5:52写道：
